[project]
name = "security_ai"
version = "0.1.0"
authors = ["Aliprf <aliprf@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]

[feature.prod.dependencies]
python = "3.12.*"      # use '3.12.*' to avoid ambiguity warning
openai = "*"
langchain = "*"
langgraph = "*"
pydantic = "*"

[feature.dev.dependencies]
pytest = "*"

[environments.prod]
features = ["prod"]

[environments.dev]
features = ["prod", "dev"]

