[project]
name = "security_ai"
version = "0.1.0"
authors = ["Aliprf <aliprf@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]


[dependencies]
flask = "*"
python = "3.12.*" 
openai = "*"
langchain = "*"
langgraph = "*"
pydantic = "*"
sentence-transformers = "*"
langchain-openai = "*"

[pypi-dependencies]
gradio = "*"
tqdm = "*"


[feature.prod.dependencies]


[feature.dev.dependencies]
pytest = "*"

[environments.prod]
features = ["prod"]

[environments.dev]
features = ["prod", "dev"]


[tasks.test]
cmd = "pytest --maxfail=1 --disable-warnings -q"
env = { PYTHONPATH = "." }


[tasks.run_script]
cmd = "python"
args = ["${file}"]
env = { PYTHONPATH = "." }


[tasks.parse]
cmd = ["python", "utilities/parser.py"]
env = { PYTHONPATH = "." }



[tasks.ce] #create_embeddings
cmd = ["python", "utilities/embedding_creator.py"]
env = { PYTHONPATH = "." }

[tasks.up]
cmd = ["python", "main.py"]
env = { PYTHONPATH = "." }

